### PR TITLE
Fix Types

### PR DESCRIPTION
**Pull request by azizhk**
So the original rationale being these types was that they followed flow types.
But certain things are not supported in both. So they might vary from time to time.

🍉 supports both `@nochange fieldName` and `@nochange() fieldName`. Tested both works now.

Fixes https://github.com/Nozbe/WatermelonDB/issues/559

### CODE REVIEW

**Comment by azizhk** [comment]
Because the types are not auto generated, was thinking of a test strategy for this. Can we add a "With Typescript" example in the examples folder and then run type check on Travis for that folder.

**Comment by radex** [comment]
> Because the types are not auto generated, was thinking of a test strategy for this. Can we add a "With Typescript" example in the examples folder and then run type check on Travis for that folder.

Yeah! I think you can just make `src/type-tests.ts` or something like that - waiting for the PR :)

**Comment by radex** [comment]
@azizhk can you add a quick note to CHANGELOG about your fixes? then I can merge

**Comment by azizhk** [comment]
> @azizhk can you add a quick note to CHANGELOG about your fixes? then I can merge

Done.

> Yeah! I think you can just make src/type-tests.ts or something like that - waiting for the PR :)

Yeah will do. Will try to make it such that it covers most of the use cases of how to type models. Will try to give PR by 1st week of March.

**Comment by radex** [comment]
thanks!

**Comment by sidferreira** [comment]
We need this deployed...

**Pull request merged**
