### PR TITLE
Improved types for SQLite and LokiJS adapters, migrations, models, the database and the logger

### PR DESCRIPTION
**Pull request by jakebloom**
I ran prettier so it looks like there are a lot of changes here. The important ones are in:

src/Database/index.d.ts
src/Model/index.d.ts
src/Schema/index.d.ts
src/Schema/migrations/index.d.ts
src/adapters/lokijs/index.d.ts
src/adapters/sqlite/index.d.ts
src/adapters/type.d.ts
src/utils/common/logger/index.d.ts

Just making these type more consistent with what is in the actual JS/flow.

### CODE REVIEW

**Comment by radex** [comment]
Great stuff! Why are there non-functional changes in the diff? Do you have a different version of Prettier running locally? Or were those files simply out of date anyway?

There's a Flow error that inadvertently appeared after one of these: https://travis-ci.com/Nozbe/WatermelonDB/jobs/208774179

**Comment by jakebloom** [comment]
> Do you have a different version of Prettier running locally? Or were those files simply out of date anyway?

Not too sure - I've removed all those, so this is just the type changes now.

**Comment by radex** [comment]
Cool, merging it now, thanks @jakebloom !

**Comment by radex** [comment]
@jakebloom btw: Have I already offered to send you 🍉 stickers? If not, and you'd like some, please do email me and I'll send a bunch your way :)

**Comment by jakebloom** [comment]
That'd be amazing, thanks @radex!

**Pull request merged**
