### PR TITLE
WIP: docs(android): update the android installation instructions in light …

### PR DESCRIPTION
**Pull request by jspizziri**
…of autolinking

https://github.com/Nozbe/WatermelonDB/issues/958

### CODE REVIEW

**Comment by jspizziri** [comment]
So... In theory I think this should be right? However, this seems to break Android release builds with the following error:

```
> Task :nozbe_watermelondb:compileReleaseKotlin FAILED
e: /app/node_modules/@nozbe/watermelondb/native/android/src/main/java/com/nozbe/watermelondb/DatabaseDriver.kt: (47, 36): Unresolved reference: BuildConfig
```

I'm not sure why that'd be the case as the [Android Docs](https://developer.android.com/studio/build/gradle-tips#share-custom-fields-and-resource-values-with-your-app-code) state that the `BuildConfig` class is generated at build-time.

**Comment by radex** [comment]
@rozPierog take a look pls, does this look right?

**Comment by rozPierog** [comment]
I'm not familiar with how React Native handles auto linking to be honest. It seems strange that it would interfere with such fundamental thing as BuildConfig, but I welcome someone more knowledgeable on this to chime in

**Review by zxcpoiu — APPROVED** [review]
This is correct.

To use this lib, user should have setup babel config and add kotlin support in build.gradle, then the rest will be handled by auto linking. ( RN >= 60+ and WatermelonDB >= 21+ )

**Comment by zxcpoiu** [comment]
FWIW: [how does autolinking works](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md) if anyone interested in.

**Comment by zxcpoiu** [comment]
@jspizziri have you tried to clear all gradle build cache? ie: `./gradlew clean`

**Comment by jspizziri** [comment]
@zxcpoiu thanks for the feedback!

1. Yes, I did run a clean, I have it built in as part of my release command:
    ```json
    "android:clean": "cd android && ./gradlew clean",
    "android:release": "npm run android:clean && cd android && ./gradlew bundleRelease",
    ```
2.  I have `babel.config.js` as follows in my project:
    ```js
    module.exports = {
       presets: ['module:metro-react-native-babel-preset'],
       plugins: [
         ['@babel/plugin-proposal-decorators', { 'legacy': true }]
       ],
    };
    ```

**Comment by zxcpoiu** [comment]
@jspizziri  I don't have this issue, it seems strange. :(

Anyway, I've research a bit and come up with a clearer solution and doc. Had Created a new PR #977 on top of cherry-picked your commit.

**Comment by radex** [comment]
Closing in favor of #977 -- thank you @jspizziri  & @zxcpoiu

**Pull request closed without merging**
