### PR TITLE
Add unsafeFetchRecordsWithSQL

### PR DESCRIPTION
**Pull request by ryan-rokusek**
This is to pick back up what @zobeirhamid started in #199.

### CODE REVIEW

**Comment by radex** [comment]
@ryan-rokusek is this PR still work in progress, or is this meant to be reviewed?

**Comment by ryan-rokusek** [comment]
@radex I meant it to be reviewed but tbh, I may have missed some stuff in the original thread. It was my understanding that rawQuery needed to be renamed to make it more clear and then it was ready to go. 

Please let me know if I'm way off base and I'm happy to rework this.

**Comment by radex** [comment]
@ryan-rokusek no, some more changes are needed:

- RawQuery extends Query is no go — it has methods that simply don't work. The method you added on Collection should just return a promise of records immediately, without extra objects — if more extensibility is necessary, someone can propose a full API later
- There are git conflicts

**Comment by ryan-rokusek** [comment]
Thanks for the feedback @radex! I'll make some mods and update the request in the next few days.

**Comment by yanielbf** [comment]
Hi, what is state of this feature?? I need to use it in my application asap. Greetings

**Comment by ryan-rokusek** [comment]
@yanielbf Sorry for the delay, work has been busy. I'm hoping to integrate radex's feedback this week.

**Comment by yanielbf** [comment]
@radex Hi radex, thank you for answer me. I will waiting for that. Can you notifyme when you do it. Greetings

**Comment by radex** [comment]
@ryan-rokusek closing this in favor of https://github.com/Nozbe/WatermelonDB/pull/557 — but thanks a lot for trying to get this finished!

**Pull request closed without merging**
