### PR TITLE
Sync diagnostics

### PR DESCRIPTION
**Pull request by radex**

### CODE REVIEW

**Comment by radex** [comment]
- added some extra info to sync logs
- open-sourced SyncLogger from NT codebase (it's simple and generic, might as well be here)

**Comment by radex** [comment]
@rozPierog can you review it this week? (or delegate to Konrad/Michu)

**Comment by radex** [comment]
@rozPierog I'm reassigning to @kokusGr ;)

**Review by kokusGr — APPROVED** [review]
LGTM 👍

**Pull request merged**
