### PR TITLE
[Travis] restart ADB and retry test on fail

### PR DESCRIPTION
**Pull request by rozPierog**
My mission is to create the most robust Android testing CI script ever. So I've made simple script to just retry test if it fails for the first time. It Should lower rate of false-negatives in CI created by some problem with ADB.  **_IT'S NOT GONNA BE FOOLPROOF_** but still better than nothing - right?

### CODE REVIEW

**Comment by radex** [comment]
So if I understand correctly: If tests fail for any reason, it will retry ONCE, correct? It doesn't have any magic to figure out reason for failure, so a legitimate tests failure will cause the test to (unnecessarily) run twice, yeah? (Not a problem, just not sure if I understand bash correctly)

**Comment by radex** [comment]
you have a syntax error :P

**Comment by rozPierog** [comment]
>if tests fail for any reason, it will retry ONCE, correct? It doesn't have any magic to figure out reason for failure, so a legitimate tests failure will cause the test to (unnecessarily) run twice, yeah? 

Well, yeah. But you've just inspired me to become a wizard and do some magic to only restart if it failed due to `no connected devices` error

**Comment by radex** [comment]
> Well, yeah. But you've just inspired me to become a wizard and do some magic to only restart if it failed due to no connected devices error

i'd avoid wizardry unless you're determined, since there might be other sources of flakiness fixed by this 😂

**Comment by radex** [comment]
thanks!

**Pull request merged**
