### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by radex**
- RN to 0.58
- other yarn dependencies updated
- travis to Xcode 10.1
- upgrade native demo dependencies
- upgrade web demo depdendencies
- updates native demo to use react-natigation v3 + fixes issue with scrollview/flatlist
- push updated web demo to ZEIT
- change 🍉 config so that LokiJS is always a dependency of Watermelon, even if you don't use it (native). There's little harm in it, and it simplifies installation

### CODE REVIEW

**Comment by radex** [comment]
I get this when trying to compile updated `examples/native`:

```
 ~/Documents/Nozbe/WatermelonDB/examples/native   update-deps ±⇕ yarn start:android
yarn run v1.13.0
$ react-native run-android
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

> Configure project :app
WARNING: API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variant.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getPackageApplication(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

> Configure project :react-native-prompt-android
WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.3.0.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
e: /Users/radex/Documents/Nozbe/WatermelonDB/examples/native/android/app/src/main/java/com/app/NativeModulesPackage.kt: (11, 103): Unresolved reference: emptyList
e: /Users/radex/Documents/Nozbe/WatermelonDB/examples/native/android/app/src/main/java/com/app/NativeModulesPackage.kt: (14, 13): Unresolved reference: arrayListOf
e: /Users/radex/Documents/Nozbe/WatermelonDB/examples/native/android/app/src/main/java/com/app/PerformancePlugin.kt: (12, 53): Unresolved reference: hashMapOf
e: /Users/radex/Documents/Nozbe/WatermelonDB/examples/native/android/app/src/main/java/com/app/PerformancePlugin.kt: (12, 82): Unresolved reference: to

> Task :app:compileDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
34 actionable tasks: 26 executed, 8 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: ./gradlew installDebug

Error: Command failed: ./gradlew installDebug
    at checkExecSyncError (child_process.js:625:11)
    at Object.execFileSync (child_process.js:643:13)
    at runOnAllDevices (/Users/radex/Documents/Nozbe/WatermelonDB/examples/native/node_modules/react-native/local-cli/runAndroid/runAndroid.js:299:19)
    at buildAndRun (/Users/radex/Documents/Nozbe/WatermelonDB/examples/native/node_modules/react-native/local-cli/runAndroid/runAndroid.js:135:12)
    at isPackagerRunning.then.result (/Users/radex/Documents/Nozbe/WatermelonDB/examples/native/node_modules/react-native/local-cli/runAndroid/runAndroid.js:65:12)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by radex** [comment]
@rozPierog ⬆️

**Comment by rozPierog** [comment]
@radex works for me :|
I've updated Gradle/Kotlin maybe now it will also work for you.

**Comment by radex** [comment]
Hmm, still didn't work — opened in Android Studio and accepted its suggestion to do… something? to Kotlin config and it works.

Had to make some changes — can you take a look at the PR, especially the latest Android commit? I had to add new items to .gitignore because Android STudio produces new junk.

Also: please check if examples works on iOS and Android

**Comment by radex** [comment]
fucking Travis, maan.

**Comment by rozPierog** [comment]
Everything seems to work fine on both iOS and Android. Please resolve Conflicts and I'll merge this PR

**Pull request merged**
