### PR TITLE
Adaptive layout

### PR DESCRIPTION
**Pull request by dipiash**
Pull request for https://github.com/Nozbe/WatermelonDB/issues/43

- Added adaptive layout
- Added smooth scrolling for iOS

### CODE REVIEW

**Comment by dipiash** [comment]
Yes I can :)

**Comment by radex** [comment]
Cool, this looks good @dipiash ! Not perfect, but much better :) Will merge when CI shows green

**Comment by dipiash** [comment]
@radex, is this test not frozen?
Already 6 hours have passed since the launch...

**Comment by radex** [comment]
Looks like it :)

Thanks, will merge next week. Send me an email if you want a 🍉 sticker, I can ship some to you :)

**Comment by dipiash** [comment]
Thanks!
I sent Email to your email address:)

**Comment by radex** [comment]
Merged — thanks!

**Pull request merged**
