### PR TITLE
[Docs]: minor tweak

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Made the license section point to the respective file.

### CODE REVIEW

**Comment by radex** [comment]
Thanks!

**Comment by jamesgeorge007** [comment]
@radex as mentioned in the docs am I eligible for the sticker pack :sweat_smile:

**Comment by radex** [comment]
have you made a non-trivial contribution? ;)

**Comment by jamesgeorge007** [comment]
Would love to know your thoughts on [Mevn-CLI](https://github.com/madlabsinc/mevn-cli)
Leave a :star: if you found it interesting :smile:

**Comment by radex** [comment]
@jamesgeorge007 I want to send you stickers, but I'd go crazy if I ran to the post office every time someone made a 1-line diff, I'm sure you understand!

There are plenty of really easy and quick tasks that would help out the community, you know! like this one: https://github.com/Nozbe/WatermelonDB/issues/42 (and here' a contributing guide: https://github.com/Nozbe/WatermelonDB/blob/master/CONTRIBUTING.md)

**Pull request merged**
