### PR TITLE
[Schema] bool → boolean

### PR DESCRIPTION
**Pull request by radex**
Just realized that schema type `bool` should be named `boolean`, since we follow JavaScript conventions, and that's how JS type is called.

I changed this and added only temporary backwards compatibility (for schema creation, not for migrations).

I think we should merge this before we ship migrations as to cause least amount of pain to users

### CODE REVIEW

**Comment by radex** [comment]
⚠️ don't merge

@rozPierog please CR

Note: CI fails because it fails on previous branch

**Comment by radex** [comment]
@kokusGr Good catch — fixed

**Comment by kokusGr** [comment]
👌

**Comment by radex** [comment]
@kokusGr ?

**Pull request merged**
