### PR TITLE
Typescript Bump

### PR DESCRIPTION
**Pull request by sidferreira**
There's a big gap between Flow and Typescript typings and this PR is trying to fix this difference.

Instead of using the current `modules` approach for TS, (almost) every JS file has its own `.d.ts` file.

From now on, `.d.ts` files needs to be updated only if a signature changes and it is easier to non TS engineers guess how to update it.

### CODE REVIEW

**Comment by sidferreira** [comment]
@radex just fixed something I forgot, tested it and TS is working just like the expected on build/dev

**Comment by radex** [comment]
Nice! I'm trying to understand - why does (almost) every JS file have a d.ts ? Is that helpful to either users of the library or helpful for TypeScript maintenance? I mean, many if not most of these are implementation details of WatermelonDB, which are never exposed to the users.

Does this mean that any change/addition/removal in any function signature in Watermelon should be mirrored in d.ts?

How did you spit out all these d.ts'es? Did you do this by hand or is there some way of speeding up this process?

**Comment by sidferreira** [comment]
> Nice! I'm trying to understand - why does (almost) every JS file have a d.ts? Is that helpful to either users of the library or helpful for TypeScript maintenance? I mean, many if not most of these are implementation details of WatermelonDB, which are never exposed to the users.

Well, IMHO yes. Basically, any exported thing is typed in Flow, with this, it is typed in TS as well. 
About exposure, technically one can use "import x from "@nozbe/wetermelondb/some/path/file" to import something very specific. In our project, it is required to override some methods and fix some needed features. Missing the TS makes me even more uncomfortable doing it.

> Does this mean that any change/addition/removal in any function signature in Watermelon should be mirrored in d.ts?

Well, shouldn't it ideally be happening already? With the .d.ts near to the file, I believe will be easier for the contributor to remember to do so.

> How did you spit out all these d.ts'es? Did you do this by hand or is there some way of speeding up this process?

Spent more hours looking for a tool than the time it took to actually do it manually. If flow types were in .flow.js files, the translation would be quite simple, but we discussed that in the past as not a good option...

**Comment by radex** [comment]
I think I'm okay with merging this, but I'm not a TypeScript guy. 

Would be nice if other TypeScript users can give their thoughts if this is a good approach or not.

**Comment by sidferreira** [comment]
> I think I'm okay with merging this, but I'm not a TypeScript guy.
> 
> Would be nice if other TypeScript users can give their thoughts if this is a good approach or not.

Most libraries I use are published like this (maybe causr they use TS only).

I believe the biggest advantage is that with the 1:1 files, won't require much knowledge to keep them up to date.

I also tried to mimic some Flow helper types to keep it as close as possible...

**Comment by radex** [comment]
Okay since no one has any comments on this, I'm merging. Thank you @sidferreira for your work on this.

**Comment by paulrostorp** [comment]
@sidferreira I'm running into issues like these when trying to use the decorators
Screenshot 2023-01-17 at 12 04 23

Have you run into these ? Have you been able to solve this issue ?

I believe the issue stems from incorrect declarations:

Instead of:
```ts
import { ColumnName } from '../../Schema'

type date = (columnName: ColumnName) => PropertyDecorator
export default date
```

I believe it should be:
```ts
import { ColumnName } from '../../Schema'

export default function date(columnName: ColumnName): PropertyDecorator
```

I can make a PR, but I wanted to get your take on it first.

**Comment by sidferreira** [comment]
@paulrostorp I did not face it, but I'm not sure we used a date field. Sadly I switched jobs and the new company doest use WDB

**Comment by radex** [comment]
@paulrostorp hey, I do encourage you to contribute that fix. Exporting it as a type and not a value does look like a bug

**Comment by enahum** [comment]
This PR seems to have been included in 0.25 and it broke almost every type definition, our project now has more than 300 type errors when applying the updated version.

**Comment by radex** [comment]
@enahum Hey, TS typings in this project are entirely community-driven - I don't have a good way to check that they are correct and rely on community feedback and PRs to improve them.

Are you saying that the refactored TS typings are entirely wrong? Or is it that there are a few issues (like what @paulrostorp mentioned) that result in those 300 errors?

If multiple people say that it's just broken and worse than before, I can revert this PR (and wait for more community contribution to fix it up).

**Comment by paulrostorp** [comment]
@radex I'll try taking a look today. Am I correct in understanding that all the `.d.ts` file are auto-generated by that `make.js` script ?

**Comment by enahum** [comment]
@radex @paulrostorp 
here the changes that I needed to make in order to fix our project

```diff
diff --git a/node_modules/@nozbe/watermelondb/DatabaseProvider/index.d.ts b/node_modules/@nozbe/watermelondb/DatabaseProvider/index.d.ts
index 7c00164..10e5388 100644
--- a/node_modules/@nozbe/watermelondb/DatabaseProvider/index.d.ts
+++ b/node_modules/@nozbe/watermelondb/DatabaseProvider/index.d.ts
@@ -1,4 +1,4 @@
-import { ElementType, ReactNode } from 'react'
+import React, { ReactNode } from 'react'
 import Database from '../Database'
 import { Provider } from './DatabaseContext'
 
@@ -11,7 +11,7 @@ export type Props = {
  * Database provider to create the database context
  * to allow child components to consume the database without prop drilling
  */
-declare function DatabaseProvider({ children, database }: Props): ElementType<Provider>
+declare function DatabaseProvider({ children, database }: Props): JSX.Element
 
 export { default as withDatabase } from './withDatabase'
 export { default as DatabaseContext, DatabaseConsumer } from './DatabaseContext'
diff --git a/node_modules/@nozbe/watermelondb/DatabaseProvider/withDatabase.d.ts b/node_modules/@nozbe/watermelondb/DatabaseProvider/withDatabase.d.ts
index b29d8aa..b70faa9 100644
--- a/node_modules/@nozbe/watermelondb/DatabaseProvider/withDatabase.d.ts
+++ b/node_modules/@nozbe/watermelondb/DatabaseProvider/withDatabase.d.ts
@@ -1,4 +1,5 @@
-import { ComponentType } from 'react'
+import type { NonReactStatics } from 'hoist-non-react-statics'
+import React, { ComponentType } from 'react'
 import type Database from '../Database'
 import { DatabaseConsumer } from './DatabaseContext'
 
@@ -8,4 +9,4 @@ type WithDatabaseProps<T> = T & {
 // HoC to inject the database into the props of consumers
 export default function withDatabase<T>(
   Component: ComponentType<WithDatabaseProps<T>>,
-): DatabaseConsumer
+): React.FunctionComponent<Omit<T, 'database'>> & NonReactStatics<T>
diff --git a/node_modules/@nozbe/watermelondb/Model/index.d.ts b/node_modules/@nozbe/watermelondb/Model/index.d.ts
index 43cd902..baefb53 100644
--- a/node_modules/@nozbe/watermelondb/Model/index.d.ts
+++ b/node_modules/@nozbe/watermelondb/Model/index.d.ts
@@ -52,14 +52,16 @@ export default class Model {
   // someTask.update(task => {
   //   task.name = 'New name'
   // })
-  update(recordUpdater: (this) => void): Promise<this>
+  update(recordUpdater: (record: this) => void): Promise<this>
 
   // Prepares an update to the database (using passed function).
   // Touches `updatedAt` if available.
   //
   // After preparing an update, you must execute it synchronously using
   // database.batch()
-  prepareUpdate(recordUpdater: (this) => void): this
+  prepareUpdate(recordUpdater: (record: this) => void): this
 
   prepareMarkAsDeleted(): this
 diff --git a/node_modules/@nozbe/watermelondb/Query/index.d.ts b/node_modules/@nozbe/watermelondb/Query/index.d.ts
index eb2bd84..eb02824 100644
--- a/node_modules/@nozbe/watermelondb/Query/index.d.ts
+++ b/node_modules/@nozbe/watermelondb/Query/index.d.ts
@@ -73,7 +73,7 @@ export default class Query<Record extends Model> {
 
   // Emits the number of matching records, then emits a new count every time it changes
   // Note: By default, the Observable is throttled!
-  observeCount(isThrottled: boolean): Observable<number>
+  observeCount(isThrottled?: boolean): Observable<number>
 
   // Queries database and returns an array with IDs of matching records
   fetchIds(): Promise<RecordId[]>
diff --git a/node_modules/@nozbe/watermelondb/QueryDescription/index.d.ts b/node_modules/@nozbe/watermelondb/QueryDescription/index.d.ts
index cf2e1e0..6910974 100644
--- a/node_modules/@nozbe/watermelondb/QueryDescription/index.d.ts
+++ b/node_modules/@nozbe/watermelondb/QueryDescription/index.d.ts
@@ -193,7 +193,7 @@ export function and(...clauses: Where[]): And
 
 export function or(...clauses: Where[]): Or
 
-export function sortBy(sortColumn: ColumnName, sortOrder: SortOrder): SortBy
+export function sortBy(sortColumn: ColumnName, sortOrder?: SortOrder): SortBy
 
 export function take(count: number): Take
 
@@ -230,7 +230,7 @@ export function experimentalJoinTables(tables: TableName<any>[]): JoinTables
 
 export function experimentalNestedJoin(from: TableName<any>, to: TableName<any>): NestedJoinTable
 
-export function unsafeSqlQuery(sql: string, values: Value[]): SqlQuery
+export function unsafeSqlQuery(sql: string, values?: Value[]): SqlQuery
 
 // const extractClauses: (clauses: Clause[]) => QueryDescription;
 
diff --git a/node_modules/@nozbe/watermelondb/decorators/children/index.d.ts b/node_modules/@nozbe/watermelondb/decorators/children/index.d.ts
index 53d3daf..b26a60a 100644
--- a/node_modules/@nozbe/watermelondb/decorators/children/index.d.ts
+++ b/node_modules/@nozbe/watermelondb/decorators/children/index.d.ts
@@ -1,4 +1,4 @@
 import { TableName } from '../../Schema'
 
-type children = (childTable: TableName<any>) => PropertyDecorator
+const children = (childTable: TableName<any>) => PropertyDecorator
 export default children
diff --git a/node_modules/@nozbe/watermelondb/decorators/date/index.d.ts b/node_modules/@nozbe/watermelondb/decorators/date/index.d.ts
index 10381e6..020654e 100644
--- a/node_modules/@nozbe/watermelondb/decorators/date/index.d.ts
+++ b/node_modules/@nozbe/watermelondb/decorators/date/index.d.ts
@@ -1,4 +1,4 @@
 import { ColumnName } from '../../Schema'
 
-type date = (columnName: ColumnName) => PropertyDecorator
+const date = (columnName: ColumnName) => PropertyDecorator
 export default date
diff --git a/node_modules/@nozbe/watermelondb/decorators/field/index.d.ts b/node_modules/@nozbe/watermelondb/decorators/field/index.d.ts
index 87625ac..520f15e 100644
--- a/node_modules/@nozbe/watermelondb/decorators/field/index.d.ts
+++ b/node_modules/@nozbe/watermelondb/decorators/field/index.d.ts
@@ -1,4 +1,4 @@
 import { ColumnName } from '../../Schema'
 
-type field = (columnName: ColumnName) => PropertyDecorator
+const field = (columnName: ColumnName) => PropertyDecorator
 export default field
diff --git a/node_modules/@nozbe/watermelondb/decorators/immutableRelation/index.d.ts b/node_modules/@nozbe/watermelondb/decorators/immutableRelation/index.d.ts
index 6a7e860..529bcd9 100644
--- a/node_modules/@nozbe/watermelondb/decorators/immutableRelation/index.d.ts
+++ b/node_modules/@nozbe/watermelondb/decorators/immutableRelation/index.d.ts
@@ -1,6 +1,6 @@
 import { ColumnName, TableName } from '../../Schema'
 
-type immutableRelation = (
+const immutableRelation = (
   relationTable: TableName<any>,
   relationIdColumn: ColumnName,
 ) => PropertyDecorator
diff --git a/node_modules/@nozbe/watermelondb/decorators/json/index.d.ts b/node_modules/@nozbe/watermelondb/decorators/json/index.d.ts
index 55de0d8..4aae413 100644
--- a/node_modules/@nozbe/watermelondb/decorators/json/index.d.ts
+++ b/node_modules/@nozbe/watermelondb/decorators/json/index.d.ts
@@ -3,6 +3,6 @@ import Model from '../../Model'
 
 type Sanitizer = (source: any, model?: Model) => any
 
-type json = (rawFieldName: ColumnName, sanitizer: Sanitizer) => PropertyDecorator
+const json = (rawFieldName: ColumnName, sanitizer: Sanitizer) => PropertyDecorator
 
 export default json
diff --git a/node_modules/@nozbe/watermelondb/decorators/relation/index.d.ts b/node_modules/@nozbe/watermelondb/decorators/relation/index.d.ts
index 9fea99e..ef7baae 100644
--- a/node_modules/@nozbe/watermelondb/decorators/relation/index.d.ts
+++ b/node_modules/@nozbe/watermelondb/decorators/relation/index.d.ts
@@ -1,7 +1,7 @@
 import { ColumnName, TableName } from '../../Schema'
 import { Options } from '../../Relation'
 
-type relation = (
+const relation = (
   relationTable: TableName<any>,
   relationIdColumn: ColumnName,
   options?: Options,
diff --git a/node_modules/@nozbe/watermelondb/decorators/text/index.d.ts b/node_modules/@nozbe/watermelondb/decorators/text/index.d.ts
index 330f187..334adbd 100644
--- a/node_modules/@nozbe/watermelondb/decorators/text/index.d.ts
+++ b/node_modules/@nozbe/watermelondb/decorators/text/index.d.ts
@@ -1,5 +1,5 @@
 import { ColumnName } from '../../Schema'
 
-type text = (columnName: ColumnName) => PropertyDecorator
+const text = (columnName: ColumnName) => PropertyDecorator
 
 export default text
```

**Comment by radex** [comment]
@enahum Awesome, thank you! I can apply this patch and ship a patch release - or if you prefer, make a PR from this patch

**Comment by paulrostorp** [comment]
@radex The patch is not complete, but only based on @enahum use case. I am making good progress on a PR.

**Comment by paulrostorp** [comment]
@radex @enahum  https://github.com/Nozbe/WatermelonDB/pull/1477

**Pull request merged**
