### PR TITLE
Encrypted SQLite DB for Android

### PR DESCRIPTION
**Pull request by afiller**
Hi, as promised in #51 hereby I provide a pull request for encrypted databases on android. It's tested (ci:check and in a test project) and working. Nevertheless I want to address some things:

1) It works with or without password, but in all of the cases it's using another SQLite implementation for android. In my tests it works perfect, but I wanted to tell you. 

2) The new library requires to be mentioned in the licenses, see https://www.zetetic.net/sqlcipher/open-source/

I did not change documentation at all. It's up to you where to mention this.

3) The password can be simply set in the SQLiteAdapter:

```
new SQLiteAdapter({
      schema: defaultSchema,
      dbName: 'myDB',
      password: 'ABC123!'
    })
```

If none is given the DB is not encrypted. Quite easy and backwards compatible.

4) I adjusted the iOS methods accordingly to be the same as in Android. The parameter password is given there as well, but simply not used. I think this makes sense for possible future changes also there.

Feel free to change what you want. :) I hope it's a valuable contribution and I would look forward to be mentioned in the contributors section - but of course that's not a "must".

Best regards,

Andreas

### CODE REVIEW

**Comment by alexandrethsilva** [comment]
hi @afiller is there any update on this here? anything I could help with? right now it seems to be only a pending conflict res, but maybe there was some back channeling I'm not aware of :)

**Comment by Overtorment** [comment]
@afiller any progress on this?

**Comment by falquinho** [comment]
@afiller Hey, good evening. I'm here to ask for some guidance if you're able to help. My project requires database encryption(late requisite, else I would not have used Watermelon) so i'm trying to port you patch to Watermelon 0.17.1.
It has some differences in the `NativeBridgeType` and `NativeDispatcher`. I've changed their functions signatures where needed to take an extra string for the password, but i keep getting the run-time error `DatabaseBridge.initialize got 5 arguments but requires 6`. It doesn't make sense to me, its args are 5: `tag, schema, password, schemaVersion and callback`.
Can you help make this patch? Can someone point me what I'm missing?

**Comment by radex** [comment]
Closed in favor of https://github.com/Nozbe/WatermelonDB/pull/907 . Thank you for your work!

**Pull request closed without merging**
