### PR TITLE
Fix build script & dev mode

### PR DESCRIPTION
**Pull request by radex**
- Fixes production build script
- Fixes dev script
- Adds option to compile dev to any folder
- Documents how to do this

### CODE REVIEW

**Comment by radex** [comment]
@rkrajewski Tests and CR? Can you check that:

- `yarn build` works (build it and then copy to Purple's app/node_modules/@nozbe/watermelondb to see if it launches on both web and native)
- `yarn dev` works (same steps as above)
- and that the development with app in the loop instructions work correctly?

**Comment by radex** [comment]
Hey @rkrajewski — can you take a look? Or delegate to @kokusGr if you prefer

**Comment by rkrajewski** [comment]
@radex I have taken a look at this already and it doesn’t work in some cases. I will give a feedback as soon as I will solve the internal Purple’s issue that this PR depends on (I mentioned it to you last friday).

**Comment by radex** [comment]
figured out in private — let's see if it works now

**Comment by radex** [comment]
Great. Feel free to merge @rkrajewski

**Pull request merged**
