### PR TITLE
Adds rawQuery functionality

### PR DESCRIPTION
**Pull request by zobeirhamid**
Adds rawQuery functionaility, but needs Flow coverage.

Usage:
```js
const tableNameCollection = database.collections.get('table_name')
tableNameCollection.unsafeFetchRecordsWithSQL('select * from ...')

database.adapter.unsafeSqlQuery('select * from ...', 'table_name')
```
Issue: #103

### CODE REVIEW

**Comment by radex** [comment]
@zobeirhamid Thanks for the PR! This is a good start, but there's a couple of things we need before I can merge this:

- [ ] Flow declarations in code
- [ ] Tests — see https://github.com/Nozbe/WatermelonDB/issues/112 for pointers as to where to add tests
- [ ] Docs update

**Comment by zobeirhamid** [comment]
@radex Thanks for the directions. Planning to work on it when I have some free time, probably in two weeks.

**Comment by servocoder** [comment]
@zobeirhamid any update on this?

**Comment by wkirby** [comment]
Any update here? This feature is pretty necessary to use WatermelonDB in any serious capacity.

**Comment by radex** [comment]
@wkirby You're welcome to contribute if you want to pick up where @zobeirhamid left off and submit a new PR :)

**Comment by zobeirhamid** [comment]
I updated the requested tasks. I only had one problem writing the tests since the raw query functionality is only implemented for SQLite and not for Loki, but since it's a new method I had to add it for the LokiJS Adapter too, but left the implementation open.

**Comment by radex** [comment]
Awesome!

> I only had one problem writing the tests since the raw query functionality is only implemented for SQLite and not for Loki,

@zobeirhamid look at this - this is a way of determining whether you're running tests in web or native mode

https://github.com/Nozbe/WatermelonDB/blob/7b1546ad4219194cf4f3a03f0ad3a56761ef2a31/src/adapters/__tests__/commonTests.js#L777

**Comment by radex** [comment]
@zobeirhamid there are still some CI issues :/  take a look at Travis CI details

**Comment by zobeirhamid** [comment]
@radex I fixed the previous issues but still get a fail even I don't see any obvious errors.

**Comment by radex** [comment]
looks like this test: https://github.com/Nozbe/WatermelonDB/pull/199/files#diff-18ce2a16e966068b4dc9aed56cd01ff8R233 gets stuck and never completes.

have you tried running native tests locally?

**Comment by zobeirhamid** [comment]
@radex On my machine, all tests are passing. I rebased the fork with the repo and tried running the tests again and they are still passing. I, to be honest, don't know what is going wrong.

**Comment by radex** [comment]
Sure, I'll try to take a look at it this friday. Thanks for working on this @zobeirhamid !

**Comment by jonnywhite** [comment]
Hey @radex 
Do you know if this is still being looked at? We are really keen for this functionality too.
Thanks!

**Comment by radex** [comment]
@jonnywhite Hey! Apologies! Probably in two weeks time, after I get back to work… I know it's taking too much time, sorry about that.

**Comment by joshuakelly** [comment]
@zobeirhamid Are you also able to do a `SUM` on a column with this PR? It's only returning a single record for me when i run the query.

**Comment by zobeirhamid** [comment]
@joshuakelly SUM is suppose to only return a single record, in fact it should return the SUM of a column for all rows.
https://www.w3schools.com/sql/trysql.asp?filename=trysql_select_sum

**Comment by radex** [comment]
Thanks for your work on this @zobeirhamid - and apologies for late replies.

This is super useful, but I have some concerns:

- why does RawQuery extend Query if it doesn't actually support most of its methods?
- what about web/Loki? It's OK if there's no support for it in the first version, but the `RawQuery` type shouldn't be geared towards `sql` only but should be more general - more like `query: AdapterQuery` 
- it seems that RawQuery is not… raw enough! I mean, it only supports queries that return a list of records. But what about queries that return, say, a number, or a list of numbers? or don't return anything (not query but raw execution)? or some other crazy SQL options I can't even think of...

I don't expect you to have all the answers :) And I'm all for iterative development approach and taking one step at a time. But I don't like doing breaking changes, and we don't want to end up with an API that sucks in the long term, so there's two options:

1. Either we discuss and figure out an API that we'll be able to extend in the future to take care of all the concerns above without breaking anything
2. Or we mark this API in such a way that it's clear it's limited in functionality and might change in the future. For example, instead of `collection.rawQuery('sql'): RawQuery; rawQuery.fetch()`, we could do `collection.unsafeFetchRecordsWithSQL(sql: SQL): Promise<Record[]>`.

Option 1 is better, and option 2 means you can just rename a few things in your PR and we can merge soon :)

**Comment by zobeirhamid** [comment]
@radex 
Thanks for the feedback. I agree with your points. I'm gonna give some thoughts about a new API design in the next couple of days. I would have just need all the supported output types, as you listed: records, numbers, and list of numbers. Are there anymore, or is there any particular place to look for the supported output types?

**Comment by radex** [comment]
> Are there anymore, or is there any particular place to look for the supported output types?

You mean in SQL in general? TBH I don't know.

Currently 🍉 standard queries (query, find, count) only fetch records, lists of records, and integers (counts of records) — but for raw queries, we don't want to be limited to that...

**Comment by zobeirhamid** [comment]
@radex Me neither :D
Alright, so basically you imagine to be able to use sqlite through watermelon? If that's the case, wouldn't that imply that code won't be transportable between web and mobile anymore?
Personally, I don't like that approach, since if you really want, you can use react-native-sqlite-storage or similar in combination with watermelon, to use raw instructions (I tried it, it works). I would prefer, a semi-raw approach where we be open to raw input, but would limit the output format with that we would allow more complex queries and maintain the transportability of the code.

**Comment by radex** [comment]
> I would prefer, a semi-raw approach where we be open to raw input, but would limit the output format with that we would allow more complex queries and maintain the transportability of the code.

What do you mean exactly?

I’m not quite sure what sort of output format can you even get from what sort of SQLite query that would affect cross-platform ness more than the fact itself that you’re using SQL. (I think it’s natural that there would also be raw queries for LokiJS). But I think you can do queries that return, say, a list of numbers (doing statistics and such on the data) that would be useful

**Comment by zobeirhamid** [comment]
It could be that I have an error in my thought process, but what I imagined is if you execute a raw select query, then you should receive your class objects instead of just raw objects, since if you want really raw operation functionality, you can just use another library.
Nevertheless, I understand if you watermelon doesn't want to depend on another library for real raw operations, if that's the case I can also do a contribution with real raw query.

**Comment by radex** [comment]
> but what I imagined is if you execute a raw select query, then you should receive your class objects

yes, of course, but again -- with sql you can also fetch numbers...

so how about we just give up for now with preparing an extensible API and just leave `Collection.fetchRawQuery(sql: SQL): Promise<Record[]>` ? I think other open source contributors which have other needs than just fetching record lists by SQL might have good ideas as for how to go about this

**Comment by vdlindenmark** [comment]
What's the status of this feature?

**Comment by radex** [comment]
@vdlindenmark waiting for response from PR author. You can read through the discussion - there isn't a lot of work left until this is mergeable, though some things need to be reworked. You are more than welcome to take over this PR and re-submit it if you want to finish it.

**Comment by zobeirhamid** [comment]
Sorry for the wait; I totally forgot about this pull request, but here it is.
Renamed the methods and etc.
Wrote the test for the adapter method, but couldn't figure out how to write the test for the collection method since it mocks the LokiJS Adapter, but since it's an unsafe method that shouldn't be too big of a deal.

**Comment by yanielbf** [comment]
@zobeirhamid hi, I'am using your fork. I builded and installed in my project and work good, but only at debug, not when generate the release . Help me please. Greetings

**Comment by radex** [comment]
thanks @zobeirhamid ! I'm closing this PR in favor of: https://github.com/Nozbe/WatermelonDB/pull/557 — it's branching off from your branch, but I had to make some changes, and couldn't push to your fork. Expect it to be merged and released next week

**Comment by code-brewer** [comment]
Failed to get record numbers.  Anythie wrong with my code? 
    The query return nothing, nor 0, nor undefined, ...

```
let num = await db.adapter.unsafeSqlQuery('posts', 'select count(1) from posts where 1=1;');
// also try unsafeSqlQuery('posts', 'select count(1) from posts;');   got the same result.
console.log("getDocsNumsBySql: return " + num); 
```

**Comment by radex** [comment]
@code-brewer unsafeSqlQuery expects a list of records… sadly other types of queries, such as a single number are not supported. You're welcome to send a pull request improving the API.

**Comment by code-brewer** [comment]
@radex  I am sorry I can't give PR because of little spare time. But I can post issues here. I did some pressure tests this week and found memory strange and unreasonably high on iOS while android seems sane.

**Pull request closed without merging**
