### PR TITLE
Add coveralls

### PR DESCRIPTION
**Pull request by radex**

### CODE REVIEW

**Comment by radex** [comment]
Does someone want to contribute and help figure out how to set up Coveralls?

**Comment by cesargdm** [comment]
What about CodeClimate? It's my personal favorite

**Comment by radex** [comment]
@cesargdm I don't have a specific preference — can you contribute an integration with CodeClimate?

**Comment by cesargdm** [comment]
@radex Sure I'll be checking

**Comment by radex** [comment]
@cesargdm Hey, did you have a chance to take a look at this? :)

**Pull request closed without merging**
