### PR TITLE
Support flipper on Android

### PR DESCRIPTION
**Pull request by leninlin**
related issue #653

### CODE REVIEW

**Comment by radex** [comment]
@rozPierog can you review this?

**Comment by leninlin** [comment]
Any updates?

**Comment by rozPierog** [comment]
Hey @leninlin sorry about the delay, will test it out and review your PR this week. Thanks for contributing!

**Comment by rozPierog** [comment]
Everything seems good! Thanks @leninlin!

**Comment by rozPierog** [comment]
@leninlin After looking at it again I had to revert that merge. Your fix is great but it might break some databases on Watermelon upgrade as place from where database is opened/created might be different between your code and previous implementation. Please ensure that your change won't break existing apps and submit PR again.

**Comment by leninlin** [comment]
@rozPierog thank you for your review. I agree that this is not a good solution.
I will think about this and do a new PR later

**Pull request merged**
