### PR TITLE
If there's nothing to delete, do not delete

### PR DESCRIPTION
**Pull request by sidferreira**
I'm using views in my DB and it tries to delete nothing on those views and causing errors

### CODE REVIEW

**Comment by radex** [comment]
do you have these error messages on hand? This shouldn't cause any errors

**Comment by sidferreira** [comment]
@radex I did the change on github website... will fix them in the next minutes

**Comment by sidferreira** [comment]
@radex 

```
[logging] cannot modify my_table because it is a view in "delete from `my_table` where id in ()"
DB Error: 1 "cannot modify my_table because it is a view"
DB Query: delete from `my_table` where id in ()
```

this query runs after `sync` for EVERY table, even if 0 records

**Comment by sidferreira** [comment]
I still wanna save some time and propose a per-table control about being part of sync or not.
In our case, we have basically 2 different sources of sync :)

**Comment by radex** [comment]
OK, the patch seems reasonable. Do you wanna add a simple test to check that adapter is not being called in this case? (hint: spy + check number of calls to an adapter method) - I can see this easily getting reverted by accident at some point

**Comment by sidferreira** [comment]
> OK, the patch seems reasonable. Do you wanna add a simple test to check that adapter is not being called in this case? (hint: spy + check number of calls to an adapter method) - I can see this easily getting reverted by accident at some point

will do it later today

**Comment by sidferreira** [comment]
@radex done

**Comment by radex** [comment]
Looks solid, thanks!

**Pull request merged**
