### PR TITLE
New docs ci

### PR DESCRIPTION
**Pull request by radex**

### CODE REVIEW

**Comment by kamicodaxe** [comment]
Hello @radex , being following and using waterlemon db for a couple of months. Want to help!

**Comment by radex** [comment]
@kamicodaxe Sounds great, which area would you like to help out with?

**Comment by kamicodaxe** [comment]
@radex I would like to provide support for existing and/or new features on the JavaScript/Typescript end. I can also further improve docs. The sync protocol, queries etc... I have been using WatermelonDB on daily basis for the last 6 months now on an invoicing SAAS (Gesmax). Just let me know what you think is urgent, and I will dive deeper in the issue.

**Comment by radex** [comment]
@kamicodaxe Sounds great! If you're familiar with TypeScript and using it with WatermelonDB, would you like to start updating code snippets in the docs to use TS typings instead of plain JavaScript? That would be very helpful to a lot of users

**Pull request merged**
