### PR TITLE
Add quotes to names in sql queries to allow keywords as table names and columns

### LINKED ISSUE #9: Column names not escaped properly
When using SQL keywords as column names, the application dies on launch.

Example:
```
tableSchema({
      name: 'ticket_statuses',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'order', type: 'string' },
      ]
    })
```

while *order* is a SQL keyword. Stacktrace shows `Syntax error near "order"`

### PR DESCRIPTION
**Pull request by sebastian-schlecht**
@radex gave this a quick shot. Is there any way to integration-test this out-of-the-box? 

Fixes #9

### CODE REVIEW

**Comment by radex** [comment]
Good work! Thank you.

Here's a good way to add an integration test: https://github.com/Nozbe/WatermelonDB/blob/master/src/adapters/__tests__/commonTests.js#L360

I'd add a new table with keywords as columns to the test schema: https://github.com/Nozbe/WatermelonDB/blob/master/src/adapters/__tests__/helpers.js

and then in the test you can test the basic functionality: insert new item to that particular table, query it, update it, delete it permanently, mark as deleted, remove deleted records. See the tests above in the commonTests file for examples of the adapter api.

Then to test it, this doesn't work on master yet, but if you check your changes on this branch: https://github.com/Nozbe/WatermelonDB/pull/13 you can do `yarn test:ios` and/or `yarn test:android` to run integration tests (run the code through SQLite).

Let me know if you run into any issues

**Comment by sebastian-schlecht** [comment]
Cool, I will fiddle with that, thanks.

**Comment by sebastian-schlecht** [comment]
Alright, added keywords to the common tests and to the test schema. Tests pass on your branch.

**Comment by radex** [comment]
Cool, I think this is good enough — although you could make the tests better by adding (or extending) a test to make sure that querying with a keyword like `order` actually works. What you had added ensures that schema, insert, and maybe update with this work, but I don't see a test that puts a keyword in query terms

**Comment by radex** [comment]
LGTM. Please tweak the changelog and let me know if you want to play a bit more with the tests as suggested in the previous comment

**Comment by radex** [comment]
Oops, actually it’s red. Run ‘yarn ci:check’ locally — there’s an eslint issue

**Comment by sebastian-schlecht** [comment]
Oh my, missed that one - updated.

**Comment by radex** [comment]
Woohoo 🎉 merged!

**Pull request merged**
