### PR TITLE
New Example with RN 0.63, React Navigation v5

### PR DESCRIPTION
**Pull request by henrymoulton**
Feedback welcome on the idea of an updated example, @radex if you have some ideas on what could be added let me know (hooks, performance comparison of JSI?).

### CODE REVIEW

**Comment by henrymoulton** [comment]
Hey @radex this is a WIP as I still have to add performance plugin for Android back in and probably overwrite the `native` folder. With Autolinking it's a pretty serious code diff from 0.59 so I decided to actually just init a new React Native project in JS. 

Let me know if you're happy with this approach.

**Comment by radex** [comment]
@henrymoulton Hi, excellent work. I don't have time right now to take a look at it, but having this example be a full replacement for the current examples, and then after merge removing the old example (no need to have two examples folders!) sounds like the right approach. As for auto linking, I really don't care either way, I assume auto linking is only a QoL nice to have and any serious RN developer has to be able to link libs manually if needed

**Comment by henrymoulton** [comment]
Sounds great @radex I'm looking to finish this one up :)

**Comment by henrymoulton** [comment]
Update: got working on iOS and Android with the performance plugin written in Java instead of Kotlin, I hope you don't mind.

I'm seeing ~500ms with 10,000 records when launching in Release mode across iOS and Android.

**Comment by henrymoulton** [comment]
I'm a little keen to add a bit more tooling/performance stuff

https://fbflipper.com/docs/setup/databases-plugin/
and https://github.com/Kudo/react-native-cli-plugin-benchmark look worthwhile investigating

**Comment by henrymoulton** [comment]
Added Flipper!

**Comment by henrymoulton** [comment]
Not too sure why CI is failing on iOS

**Comment by radex** [comment]
@henrymoulton Don't worry about that bit, it's unrelated - i fixed it on a branch

**Comment by radex** [comment]
@henrymoulton Please merge master into this branch

**Comment by henrymoulton** [comment]
@radex sorry for the delay, that's now done :)

**Comment by radex** [comment]
@henrymoulton Hmm, so don't we want to replace the previous example/native with this one?

**Comment by henrymoulton** [comment]
Was thinking originally to do in a followup PR

**Review by radex — APPROVED** [review]

**Comment by radex** [comment]
@henrymoulton OK, looks quite good to me, so I'm going to merge. I hope to see that followup PR :)

**Pull request merged**
