### PR TITLE
Migrations — part 2

### PR DESCRIPTION
**Pull request by radex**
- Clean up
- Improve Flow typing
- add `migrationsExperimental` prop to SQLiteAdapter and LokiJSAdapter
- validate that migrations passed to adapter are correct
- route migrations object in LokiJSAdapter to Executor thread
- migration execution will be hooked up in later PRs

### CODE REVIEW

**Comment by radex** [comment]
⚠️ don't merge - parent branch

@kokusGr CR please

**Comment by radex** [comment]
@rozPierog the integration test fails on Android (yarn test:android):

```
> Task :app:connectedReleaseAndroidTest
Starting 1 tests on Nexus_5X_API_25_x86(AVD) - 6.0

com.nozbe.watermelonTest.BridgeTest > testBridge[Nexus_5X_API_25_x86(AVD) - 6.0] FAILED
        java.lang.AssertionError: watermelondb/adapters/sqlite: validates adapter options  ❌
        expect(function).toThrowError(regexp)
```

weird, since it tests the exact same code as on iOS (JS-only). Can you take a look, maybe you can figure it out?

**Comment by kokusGr** [comment]
Except for CI fail 👌

**Comment by radex** [comment]
nvm, i know what's up

**Comment by radex** [comment]
fixed @kokusGr.

@mobily want to take a second look?

**Pull request merged**
