### PR TITLE
Fix compile for schemes with whitespace

### PR DESCRIPTION
**Pull request by vdlindenmark**
This fixed https://github.com/Nozbe/WatermelonDB/issues/295

### CODE REVIEW

**Comment by radex** [comment]
> \"${DERIVED_SOURCES_DIR}\"/*-Swift.

Huh, I didn't know that could work. @vdlindenmark just to be 100% sure: you tested the fix and it works, right?

**Comment by vdlindenmark** [comment]
Yeah I've checked! First I had `\"${DERIVED_SOURCES_DIR}/*-Swift.h\"` but it then search literally for `*-Switf.h` So I ended up with this code.

Schermafbeelding 2019-03-26 om 13 19 29

**Comment by radex** [comment]
Great! Thanks @vdlindenmark

**Comment by vdlindenmark** [comment]
Hmmm... I see a ` - ` and `alpha`(with BuildProductsPath) folder inside the root of my project... When I removed those folders and archive the project again and they're back... But don't know if this script did create the folders.

Sorry I didn't notice those folders before

**Comment by radex** [comment]
Ahh… that makes sense. Sorry, I'll revert your fix for now — I think it compiled for you only by accident — if you hit Build → Clean, it would fail, since it wouldn't actually copy the files as needed

**Comment by crrobinson14** [comment]
@radex Is there a reason this fix was reverted? I am having the same issue as @vdlindenmark (schemas with spaces in their names) and manually applying the quote-wrappers fixes it for me. I think this is still needed:

```
Last lines of the Xcode's build log:
cp: /Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-aezkzgmwhwdxfucspirggdxchyyl/Build/Intermediates.noindex/ArchiveIntermediates/Awarnys is a directory (not copied).
cp: Dev/IntermediateBuildFilesPath/WatermelonDB.build/Release-iphoneos/WatermelonDB.build/DerivedSources/*-Swift.h: No such file or directory
cp: /Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-aezkzgmwhwdxfucspirggdxchyyl/Build/Intermediates.noindex/ArchiveIntermediates/Awarnys is a directory (not copied).

** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution Copy\ module\ map /Users/chad/Library/Developer/Xcode/DerivedData/Awarnys-aezkzgmwhwdxfucspirggdxchyyl/Build/Intermediates.noindex/ArchiveIntermediates/Awarnys\ Dev/IntermediateBuildFilesPath/WatermelonDB.build/Release-iphoneos/WatermelonDB.build/Script-6E660D6B213BCD9700189354.sh
```

**Comment by radex** [comment]
Yeah, this wasn't a correct fix

**Comment by vdlindenmark** [comment]
I't did only compile because we compiled the project successfully earlier :-p

**Pull request merged**
